### PR TITLE
Makefile: Set kernel name

### PR DESCRIPTION
**Pull request by regalstreak**
Just set the kernel name so that the user knows!

### CODE REVIEW

**Comment by xdevs23** [comment]
Where will the user see it?
I already have an extra for kernel version in device info, see https://github.com/xdevs23/android_kernel_oneplus_msm8994/commit/5bc69ca4806804e88c6f39d3f8f22081ed6224e8#diff-1a9a7005ec948c12dfd7a511203ddeb6R49

**Comment by regalstreak** [comment]
It will be on the kernel version setting.
See like

```
3.10.84-yourkernelnamegoeshere-perf+
user@hostname
othershiz
```

**Comment by xdevs23** [comment]
Is already there:

xosbb10

**Comment by regalstreak** [comment]
haha lool
there are 2 methods for doing that
I guess you did the other one :p

**Comment by regalstreak** [comment]
btw why still 3.10.49

**Comment by xdevs23** [comment]
You're right mate.

**Comment by xdevs23** [comment]
What is the new version?

84?

**Comment by regalstreak** [comment]
3.10.84

**Comment by regalstreak** [comment]
halogenOS also has that

**Comment by xdevs23** [comment]
Hm, how do I get the new version?

**Comment by regalstreak** [comment]
upstream maybe? Or base it off the new kernel source

**Comment by xdevs23** [comment]
How did you do it?

**Comment by regalstreak** [comment]
try to merge the halogenOS source? Telegram would be better tho.

**Comment by xdevs23** [comment]
k

**Comment by xdevs23** [comment]
dis gud? https://github.com/xdevs23/android_kernel_oneplus_msm8994/commit/64a6857528191bfe9e554729c1951a2ee750c4d2

Seems that almost everything was already merged lol.

**Comment by FireLord** [comment]
lol better edit the defconfig @regalstreak

**Comment by regalstreak** [comment]
It's the same thing and the same property in the defconfig. So it doesn't matter actually. I used to do it this way always.

**Comment by xdevs23** [comment]
LMAO

**Pull request closed without merging**
